<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<ul>

    <?php foreach ($items as $item) { ?>

        <?php if ($item['is_dir']) { ?>
            <li><a href="index.php?path=<?=$item['file_path'] ?>"><?= $item['file_name'] ?></a></li>
        <?php } else { ?>
            <li><a href="files.php?file=<?=$item['file_path'] ?>"><?= $item['file_name'] ?></a> <?=$item['file_size'] ?></li>
        <?php } ?>

    <?php } ?>

</ul>

</body>
</html>